apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phaseone.fullname" . }}-gateway
  labels:
    {{- include "phaseone.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  replicas: {{ .Values.replicaCount.gateway }}
  selector:
    matchLabels:
      {{- include "phaseone.gatewaySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "phaseone.gatewaySelectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "phaseone.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: gateway
          image: {{ include "phaseone.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.gateway.command | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.gateway.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "phaseone.configMapName" . }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "phaseone.databaseUrlSecretName" . }}
                  key: {{ include "phaseone.databaseUrlSecretKey" . }}
            {{- include "phaseone.secretEnv" . | nindent 12 }}
            {{- with .Values.gateway.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.gateway.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.gateway.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- with .Values.gateway.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.gateway.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
