apiVersion: v1
kind: Service
metadata:
  name: phaseone-gateway
  labels:
    app.kubernetes.io/name: phaseone
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: phaseone
    app.kubernetes.io/component: gateway
